#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <level> <text>"
    exit 1
fi

LEVEL=$1
TEXT=$2

if [ -z "$LEVEL" ]; then
    echo "Color is not set"
    exit 1
fi

if [ -z "$TEXT" ]; then
    echo "Text is not set"
    exit 1
fi

DEFAULT='\033[0m'
ERROR='\033[0;31m'
SUCCESS='\033[0;32m'
WARNING='\033[0;33m'
STATUS='\033[0;35m'
INFO='\033[0;36m'
MSG='\033[0;37m'

case $LEVEL in
    error)
        echo -e "${ERROR}${TEXT}${DEFAULT}"
        ;;
    success)
        echo -e "${SUCCESS}${TEXT}${DEFAULT}"
        ;;
    warning)
        echo -e "${WARNING}${TEXT}${DEFAULT}"
        ;;
    status)
        echo -e "${STATUS}${TEXT}${DEFAULT}"
        ;;
    info)
        echo -e "${INFO}${TEXT}${DEFAULT}"
        ;;
    msg)
        echo -e "${MSG}${TEXT}${DEFAULT}"
        ;;
    *)
        echo "Invalid level"
        exit 1
        ;;
esac
