#!/usr/bin/env bash

secret_length=$1

if [ -z "$secret_length" ]; then
    secret_length=32
fi

openssl rand -base64 $secret_length | tr -d \\n | pbcopy

if [ $? -eq 0 ]; then
    echo "Secret copied to clipboard"
else
    echo "Failed to generate secret"
fi
