#!/usr/bin/env bash

BRANCH_NAME=$(basename $1)
SESSION_NAME=$(tmux display-message -p "#S")
CLEAN_NAME=$(echo $BRANCH_NAME | tr "./" "__")
TARGET="$SESSION_NAME:$CLEAN_NAME"

if ! tmux has-session -t $TARGET 2> /dev/null; then
    tmux neww -dn $CLEAN_NAME
fi

shift
tmux send-keys -t $TARGET "$*
